language: python
python:
- '3.5'
- '3.6'
- '3.7'
- pypy3
install:
- pip install -e .[testing,doc]
script:
- pylint --rcfile=.pylintrc mitba tests
- pytest tests
- sphinx-build -a -W -E doc build/sphinx/html
deploy:
  provider: pypi
  user: infradev
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Infinidat/mitba
    python: '3.6'
  password:
    secure: cSS7aK+d4iLW0v0Tm14PgZJbBvFPI3MQQ+eI8nY9wujrcLFR6q8RFraLZo3RkZq9zHbYDmtPrXEaRlvVTmIup+KaGvkjt9e+K2lC8fpQeNRgMWHU8N43WVNhyiZsZIAaQ4c9iS6/NdiO3GDARrlm1j8Mw/xY5MIACAZBK4HSlyxrsySFEScpGOqwYn76kJgH4Q8+eBj+lkvCW8gQKniwqxD8gnYwQFqvzacNPHvhey3dk7YxqBaMgtO7kzdCSKEvlbthqWXS+7z68UsH+RXaThrrz9C/hT9P8VD/LlK3ESsxSHZ6bMuuWv/29zvYq2dCkICsyiGf7QbNAbGyPviKPuaaxf8zT/EQzdvM9lqBRrsdkrLzyuAjFnjmb+YEkEJ6tOkU8gG7SmKLVE6tUkpS5TzJI+ByUo0cNfiSd/WyYg3mV4sXTP6UjfN2z6/WQIzUAif9dkGw8n0F4XSxKOlzY0thoFm/mo/zN493wNf59wOg7FXjptMi0iUvn639+rSv0j44x8DJ63yi4v66L2Oe4c/XEM8FScEyx4z5KJuGcNvu1std3btM8WtE2B/bQIYkDI0WDmculyby6NDAQHYVyrZvA8Va/ml+7Xyiqx6k8W7dZsqmFm7JKkjydL8lGfZGhdEPZV7lCiKwQEX/6DeTAjNi5rtAUXBMjqO3QoryXtc=
